### ISSUE TITLE
missing packages

### ISSUE THREAD

**Issue by jabbalaci** [techcentaur/PyLex#2]
Add click and lxml to requirements.txt .
For ast I got an error, thus I had to remove it.
Also, add the shebang line to the beginning:

    #!/usr/bin/env python3

**Comment by techcentaur** [comment]
Thanks, I've updated requirements.txt and the shebang line. Also, why did you get an error while compiling the code with ast?

**Comment by jabbalaci** [comment]
I just wanted to install the packages from requirements.txt and pip dropped an error that ast cannot be installed.

**Comment by techcentaur** [comment]
Yes, it was a mistake to write ast in requirements, since ast is already installed in python module. Thank you for reminding me.
